update ami parameter and add a clean-up jenkins job

diff --git a/ci/jenkins/jobs/macros.yaml b/ci/jenkins/jobs/macros.yaml
--- a/ci/jenkins/jobs/macros.yaml
+++ b/ci/jenkins/jobs/macros.yaml
@@ -198,3 +198,17 @@
           if [ "$success" != "ok" ]; then
             exit 1
           fi
+
+- builder:
+    name: builder-capa-aws-clean-up
+    builders:
+      - shell: |-
+          #!/bin/bash
+          for clustername in `kubectl get clusters -A --no-headers | grep test | awk '{print $1}'`;
+          do 
+              echo $clustername;
+              timeout 2m echo ./ci/jenkins/test-vmc.sh --cluster-name "$clustername" --cleanup-only --provider aws
+              if [[ $? == 124 ]]; then
+                  echo "#error# clean up job of ${clustername} time out"
+              fi
+          done
